version: 2.1
orbs:
  node: circleci/node@4.7.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - attach_workspace:
          at: .
      - run:
          command: npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .
  eslint:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - attach_workspace:
          at: .
      - run:
          command: npm run lint
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - eslint:
          requires:
            - build
      - aws-elastic-beanstalk/deploy:
          context: aws-creds
          application-name: react-docker
          environment-name: Reactdocker-env
          filters:
            branches:
              only:
                - main
          label: version-<<pipeline.number>>
          requires:
            - build
